---
title: "R Notebook"
output: html_notebook
---

```{r}

library(here)
library(sf)
library(leaflet)
library(mapedit)
library(leafpop)
library(tidyverse)

# Set relative file location
here::i_am("code_prototyping.Rmd")

### Load data
lcat_layers <- st_layers(here("fromBLM", "Ian_Lotic_LCAT_Layers.gdb"))
indicators <- st_read(here("fromBLM", "Ian_Lotic_LCAT_Layers.gdb"), layer = "I_Indicators")
defaultconds <- st_read(here("fromBLM", "Ian_Lotic_LCAT_Layers.gdb"), layer = "A_DefaultConditions") %>% as.data.frame()
defaultBMgroups <- st_read(here("fromBLM", "Ian_Lotic_LCAT_Layers.gdb"), layer = "A_DefaultBenchmarkGroups") %>% as.data.frame()

pal <- colorFactor(c("navy", "red", "green"), domain = c("Targeted", "RandomGRTS", "RandomSystematic"))

map <- indicators %>% st_transform(4326) %>%
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    radius = 3,
    color = ~pal(PointSelectionType),
    stroke = FALSE, fillOpacity = 0.5,
    label = ~PointID) %>%
  addProviderTiles("Esri.WorldTopoMap",
    group = "Esri.WorldTopoMap") %>%
  addProviderTiles("Esri.WorldImagery",
    group = "Esri.WorldImagery") %>%
  addLayersControl(
    baseGroups = c("Esri.WorldTopoMap",
                   "Esri.WorldImagery"),
    # position it on the topleft
    position = "topleft") %>%
  addLegend(pal = pal, values = ~PointSelectionType, opacity = 1)

map
```

```{r}

bmMedValues <- defaultBMgroups %>% group_by(Indicator) %>% summarise(ModerateBenchmark1 = median(ModerateBenchmark1, na.rm = TRUE),
                                                   MajorBenchmark1 = median(MajorBenchmark1, na.rm = TRUE),
                                                   ModerateBenchmark2 = median(ModerateBenchmark2, na.rm = TRUE),
                                                   MajorBenchmark2 = median(MajorBenchmark2, na.rm = TRUE)) 

# Get most common operator 
operatorColNames <- defaultBMgroups %>% select(contains("Rel")) %>% names()
bmOperatorsCount <- defaultBMgroups %>% group_by(Indicator) %>% count(MajorToModerateRel1, 
                                                                    MinimalToModerateRel1,
                                                                    MinimalToModerateRel2,
                                                                    MajorToModerateRel2,
                                                                    MajorToMinimalRel1,
                                                                    MajorToMinimalRel2,
                                                                    IncreaserDecreaser,
                                                                    ConditionCategoryNum,
                                                                    sort = FALSE)

bmCategoryCount <- defaultBMgroups %>% group_by(Indicator) %>% count(ConditionCategoryNum,
                                                                    sort = FALSE)

comb <- full_join(bmOperatorsCount, bmCategoryCount, by = "Indicator", keep = TRUE)

```


```{r}
## joining indicator and benchmarks
bm <- read_csv(here("sample_data", "fishbearing_bm_group.csv"))
ind <- read_csv(here("sample_data", "wy_landerPts.csv"), col_types = cols(.default = "c")) %>% head(1)

indLong <- ind %>% pivot_longer(cols = everything(), names_to = "attribute", values_to = "value")

dat <- full_join(indLong, bm, by = join_by(attribute == benchmark), keep = TRUE)

```

```{r}
bm <- read_csv("appData/default_benchmark_and_operators.csv")
wy <- read_csv("sample_data/wy_landerPts.csv")

wySelect <- wy %>% select(c('EvaluationID','BLM_AdminState','EcoregionStreamSize','ProtocolType','StreamOrder','SampledMidLatitude','SampledMidLongitude', bm$Indicator))


wylong <- wySelect %>% pivot_longer(-c('EvaluationID','BLM_AdminState','EcoregionStreamSize','ProtocolType','StreamOrder','SampledMidLatitude','SampledMidLongitude'), 
                                    names_to = "Indicator", 
                                    values_to = "value")

indicatorsWithBenchmarks <- inner_join(wylong, bm, by = "Indicator", relationship = "many-to-many")
indicatorsWithBenchmarks <- inner_join(wy1, bm, by = "Indicator")

IndicatorValuesBenchmarks <- indicatorsWithBenchmarks
```



```{r}
dat <- determine_reach_conditions(wy, bm, 3)

dat2 <- dat %>% pivot_wider(id_cols = !value, names_from = Indicator, values_from = Condition, names_glue = "{Indicator}{'Condition'}")

reachConditionsWide <- dat %>% 
      pivot_wider(id_cols = !value, names_from = Indicator, values_from = Condition, names_glue = "{Indicator}{'Condition'}")
    
datfinal <- left_join(wy, dat, by = "EvaluationID")


```


```{r}
bm <- read_csv("appData/default_benchmark_and_operators.csv")
wy <- read_csv("sample_data/wy_landerPts.csv") %>%
  st_as_sf(coords = c("SampledMidLongitude", "SampledMidLatitude"), crs = 4269)
dat <- determine_reach_conditions(wy, bm, 3)
condition_summary_table(dat, "PctFinesLessThan2mm")
condition_summary_table(dat, "FloodplainConnectivity")


id <- read_csv("sample_data/all_idaho.csv") %>%
  st_as_sf(coords = c("SampledMidLongitude", "SampledMidLatitude"), crs = 4269)
dat <- determine_reach_conditions(id, bm, 3)
cond_sum <- condition_summary_table(dat, "PctFinesLessThan2mm")
condition_summary_table(dat, "FloodplainConnectivity")

library(reactable)
reactable(dat,
          wrap = FALSE,
          fullWidth = TRUE,
          defaultColDef = colDef(minWidth = 250),
          style = list(maxWidth = 16000))

```


```{r}
library(ggdist)
library(gghalves)
selectedVars <- c("PctFinesLessThan2mm", "FloodplainConnectivity")
selectedVars <- c("PctFinesLessThan2mm", "PctFinesLessThan2mmCondition")

p <- dat %>% st_drop_geometry() %>% select(any_of(selectedVars)) %>%
  pivot_longer(cols = everything(), names_to = "indicator", values_to = "value") %>%
  ggplot(aes(x = indicator, y = value)) +
    geom_boxplot() +
    theme_minimal() +
    facet_wrap("indicator")

dat %>% st_drop_geometry() %>% select(any_of(selectedVars)) %>%
  ggplot(aes(x = indicator, y = value)) +
    geom_boxplot() +
    theme_minimal() +
    facet_wrap("indicator")

p
ggplotly(p)

dat %>% st_drop_geometry() %>% select(any_of(selectedVars)) %>%
  pivot_longer(cols = everything(), names_to = "indicator", values_to = "value") %>%
ggplot(aes(x = indicator, y = value)) + 
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.3, 
    point_colour = NA) + 
  geom_boxplot(
    width = .25, 
    outlier.shape = NA
  ) +
  geom_point(
    size = 1.5,
    alpha = .2,
    position = position_jitter(
      seed = 1, width = .1
    )
  ) + 
  coord_cartesian(xlim = c(1.2, 1.3), clip = "off") +
  theme_minimal()

p

v <- "PctFinesLessThan2mm"

conditiosBoxplot <- function(benchmark) {

  selectedVars <- c(benchmark, paste0(v, "Condition"))

plotdat <- dat %>% st_drop_geometry() %>% select(any_of(selectedVars)) %>%
  pivot_longer(cols = -selectedVars[2], names_to = "indicator", values_to = "value") %>%
  dplyr::rename(condition = selectedVars[2])

  p <- ggplot(plotdat, aes(x = indicator, y = value)) + 
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.3, 
    point_colour = NA) + 
  geom_boxplot(
    width = .25, 
    outlier.shape = NA
  ) +
  geom_point(
    aes(color = condition),
    size = 3,
    alpha = .7,
    position = position_jitter(
      seed = 1, width = .1
    )
  ) + 
  coord_cartesian(xlim = c(1.2, 1.3), clip = "off") +
  theme_minimal()
  
  p
}

```

